version: "3"

services:
    db:
        image: postgres
        container_name: "postgres_db"
        environment: 
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=toor
            - POSTGRES_DB=test_db
        ports: 
            - "5432:5432"
        volumes: 
            - "./db:/var/lib/postgresql/data/"
            - "./scripts/creata_table.sql:/docker-entrypoint-initdb.d/create_table.sql"
        
    scraper:
        build: ../webscraper
        depends_on: 
            - db
    
    api:
        build: ../api
        environment: 
            - FLASK_APP=main.py
        ports:
            - "5000:5000"
        depends_on: 
            - db
            - scraper
        